# Generated by Django 3.2.7 on 2021-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_location_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
