# Generated by Django 3.2.7 on 2021-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_location_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='grid_x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='grid_y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
