# Generated by Django 3.2.7 on 2021-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_auto_20211003_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='grid_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='grid_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
